name: qaza_e_umri
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0
environment:
  sdk: ">=3.4.3  <3.19.6"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  share_plus: ^7.1.0
  shared_preferences: ^2.2.0
  flutter_local_notifications: ^17.1.2
  flutter_datetime_picker_plus: ^2.1.0
  url_launcher: ^6.1.14
  firebase_auth: ^4.7.2
  google_sign_in: ^6.1.5
  font_awesome_flutter: ^9.0.0
  provider: ^5.0.0
  get: ^4.3.8
  flutter_native_splash: ^2.3.2
  firebase_core: ^2.32.0
  cloud_firestore: ^4.5.1
  flutter_login_facebook: ^1.8.0
  fancy_shimmer_image: ^2.0.3
  sizer: ^2.0.15
  gap: ^3.0.1
  flutter_spinkit: ^5.2.0
  google_mobile_ads: ^3.0.0
  another_flushbar: ^1.12.30
  firebase_messaging: ^14.9.4
  timezone: ^0.9.3
  form_validator: ^2.1.1
  flutter_facebook_auth: ^7.0.1
  http: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/